// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbIjIhkZnmIOzdbMF2gJwL8a8UL3RF9UI',
    appId: '1:456735030254:web:6ade2e206c31ec12cdacff',
    messagingSenderId: '456735030254',
    projectId: 'deshawa-social-app',
    authDomain: 'deshawa-social-app.firebaseapp.com',
    storageBucket: 'deshawa-social-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjWw-QUeFvFoJmtJ4Ex0kEwxv0nbv1kNw',
    appId: '1:456735030254:android:4ab13ef09cd737e2cdacff',
    messagingSenderId: '456735030254',
    projectId: 'deshawa-social-app',
    storageBucket: 'deshawa-social-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOJH7iB0X8FOz6-cNP9CEcCWtfH-W3Ssc',
    appId: '1:456735030254:ios:8da86a312a9ba2a5cdacff',
    messagingSenderId: '456735030254',
    projectId: 'deshawa-social-app',
    storageBucket: 'deshawa-social-app.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOJH7iB0X8FOz6-cNP9CEcCWtfH-W3Ssc',
    appId: '1:456735030254:ios:8da86a312a9ba2a5cdacff',
    messagingSenderId: '456735030254',
    projectId: 'deshawa-social-app',
    storageBucket: 'deshawa-social-app.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbIjIhkZnmIOzdbMF2gJwL8a8UL3RF9UI',
    appId: '1:456735030254:web:a728492b55f9d5decdacff',
    messagingSenderId: '456735030254',
    projectId: 'deshawa-social-app',
    authDomain: 'deshawa-social-app.firebaseapp.com',
    storageBucket: 'deshawa-social-app.firebasestorage.app',
  );
}
